
### A glimspe to the datapaper "BIRD-WINDOW COLLISIONS: a comprehensive dataset for the Neotropical region" (Piratelli et al. 2025) ###

# Required libraries; if not installed, use: install.packages(c("dplyr","ggplot2","grid","sp","cowplot),dependencies=T)

library(dplyr)
library(ggplot2)
library(grid)
library(sp)
library(cowplot)

# Set a work directory (path to the BWC_Neotropical_region.csv file in your computer)
setwd("FILE_LOCATION")

# Read the BWC_Neotropical_region.csv file
BWC_Neotropics=read.csv("BWC_Neotropical_region.csv")

# Below is a code provided to explore the database, which can be used to replicate all figures in the data paper.

# Figure 1 (Number of BWCs per year and country)
records_by_year=BWC_Neotropics%>%filter(!is.na(Year),Year!="Unknown")%>%mutate(Year=as.numeric(Year))%>%count(Year);records_by_country=BWC_Neotropics%>%filter(!is.na(Country))%>%count(Country)%>%arrange(desc(n));main_plot=ggplot(records_by_year,aes(x=Year,y=n))+geom_area(fill="#2fb6de")+geom_line(color="dark blue",linewidth=1)+labs(x="Year",y="Number of records")+scale_y_continuous(expand=c(0,0))+theme_classic();inset_plot=ggplot(records_by_country,aes(y=reorder(Country,n),x=n))+geom_bar(stat="identity",width=0.5,col="dark blue",fill="#2fb6de",alpha=0.3)+scale_x_continuous(expand=c(0,0),limits=c(0,max(records_by_country$n,1550)))+theme_classic()+xlab("Number of records")+theme(axis.title.y=element_blank());ggdraw()+draw_plot(main_plot)+draw_plot(inset_plot,x=0.125,y=0.47,width=0.5,height=0.5)

# Figure 2 (Geographic distribution of the gathered BWCs)
latlong=BWC_Neotropics[!is.na(BWC_Neotropics$Longitude)&!is.na(BWC_Neotropics$Latitude),];latlong=latlong[latlong$Longitude!="Unknown"&latlong$Latitude!="Unknown",];latlong$Longitude=as.numeric(as.character(latlong$Longitude));latlong$Latitude=as.numeric(as.character(latlong$Latitude));latlong=latlong[!is.na(latlong$Longitude)&!is.na(latlong$Latitude),];coordinates(latlong)=~Longitude+Latitude;proj4string(latlong)=CRS("+proj=longlat +datum=NAD83");latlong_df=as.data.frame(latlong);names(latlong_df)[names(latlong_df)=="Longitude"]="x";names(latlong_df)[names(latlong_df)=="Latitude"]="y";ggplot()+borders("world",regions=c("Brazil","Uruguay","Argentina","FrenchGuiana","Suriname","Colombia","Venezuela","Bolivia","Ecuador","Chile","Paraguay","Peru","Guyana","Panama","CostaRica","Nicaragua","Honduras","ElSalvador","Belize","Guatemala","Mexico","TrinidadandTobago","Caribe","PuertoRico","DominicanRepublic","Haiti","Jamaica","Cuba","Bahamas","Antiles","Dominica","Saba"),fill="grey95",col="grey60",linewidth=0.5)+geom_point(data=latlong_df,aes(x=x,y=y),col="#03627e",fill="#2fb6de",alpha=0.8,size=2.5,shape=24)+labs(x="Longitude",y="Latitude")+theme_light()

# Figure 3 (Number of BWCs per locality)
records_by_locality=BWC_Neotropics%>%filter(!is.na(Locality))%>%count(Locality)%>%arrange(desc(n));ggplot(records_by_locality[c(1:30),],aes(x=n,y=reorder(Locality,n)))+geom_bar(stat="identity",width=0.7,col="dark blue",fill="#2fb6de")+labs(x="Number of records",y="")+scale_x_continuous(expand=c(0,0))+theme_classic()

# Figure 4 (Number of BWCs by month)
records_by_month=BWC_Neotropics%>%filter(Month!="Unknown"&Month!="")%>%count(Month);records_with_na=BWC_Neotropics%>%filter(Month=="Unknown"|Month=="")%>%summarise(n=n())%>%mutate(Month="Unknown");records_by_month=bind_rows(records_by_month,records_with_na);months=c("January","February","March","April","May","June","July","August","September","October","November","December","Unknown");records_by_month$Month=factor(records_by_month$Month,levels=months);ggplot(records_by_month,aes(x=Month,y=n,fill=Month=="Unknown"))+geom_bar(stat="identity",col="dark blue",width=0.5)+scale_fill_manual(values=c("#2fb6de","white"),guide="none")+labs(y="Number of records",x="")+theme_classic()+theme(axis.text.x=element_text(angle=35,hjust=1))+scale_y_continuous(expand=c(0,0))

# Figure 5 (Number of BWCs by Order (all), and top species) 
records_by_order=BWC_Neotropics%>%filter(!is.na(Order))%>%count(Order)%>%arrange(desc(n))%>%mutate(color=case_when(row_number()==1~"#03627e",row_number()==2~"#2fb6de",row_number()==3~"#afe2f1",TRUE~"white"));main_plot=ggplot(records_by_order%>%filter(Order!=""),aes(x=n,y=reorder(Order,n),fill=color))+geom_bar(stat="identity",width=0.7,col="black")+scale_fill_manual(values=c("#03627e","#2fb6de","#afe2f1","white"))+labs(x="Number of records",y="")+scale_x_continuous(expand=c(0,0),limits=c(0,2600))+theme_classic()+theme(legend.position="none")+geom_segment(aes(x=570,y=22,xend=900,yend=12),color="#2fb6de",linewidth=1)+geom_segment(aes(x=440,y=21,xend=900,yend=5),color="#afe2f1",linewidth=1)+geom_segment(aes(x=720,y=22.3,xend=1000,yend=20),color="#03627e",linewidth=1);passeriformes=ggplot(BWC_Neotropics%>%filter(Order=="Passeriformes")%>%count(Species,name="n")%>%slice_max(n,n=10),aes(x=n,y=reorder(Species,n)))+geom_bar(stat="identity",width=0.7,col="black",fill="#03627e")+labs(x="",y="")+theme(axis.text.y=element_text(face="italic"),axis.text.x=element_blank(),axis.ticks.x=element_blank())+scale_x_continuous(expand=c(0,0),limits=c(0,260))+theme_classic()+theme(plot.title=element_text(size=10),panel.background=element_blank(),plot.background=element_blank())+ggtitle("Passeriformes")+theme(axis.text.y=element_text(face="italic"));columbiformes=ggplot(BWC_Neotropics%>%filter(Order=="Columbiformes")%>%count(Species,name="n")%>%slice_max(n,n=10),aes(x=n,y=reorder(Species,n)))+geom_bar(stat="identity",width=0.7,col="black",fill="#2fb6de")+labs(x="",y="")+theme(axis.text.y=element_text(face="italic"),axis.text.x=element_blank(),axis.ticks.x=element_blank())+scale_x_continuous(expand=c(0,0),limits=c(0,260))+theme_classic()+theme(plot.title=element_text(size=10),panel.background=element_blank(),plot.background=element_blank())+ggtitle("Columbiformes")+theme(axis.text.y=element_text(face="italic"));apodiformes=ggplot(BWC_Neotropics%>%filter(Order=="Apodiformes")%>%count(Species,name="n")%>%slice_max(n,n=10),aes(x=n,y=reorder(Species,n)))+geom_bar(stat="identity",width=0.7,col="black",fill="#afe2f1")+labs(x="Number of records",y="")+scale_x_continuous(expand=c(0,0),limits=c(0,260))+theme_classic()+theme(plot.title=element_text(size=10),panel.background=element_blank(),plot.background=element_blank())+ggtitle("Apodiformes")+theme(axis.text.y=element_text(face="italic"));ggdraw()+draw_plot(main_plot)+draw_plot(passeriformes,x=0.45,y=0.65,width=0.5,height=0.3)+draw_plot(columbiformes,x=0.445,y=0.363,width=0.5,height=0.3)+draw_plot(apodiformes,x=0.4,y=0.08,width=0.55,height=0.3)

# Figure 6 (one figure per inset)
# a)
survivorship=BWC_Neotropics%>%count(Survivorship)%>%arrange(desc(n));ggplot(survivorship,aes(x=1.5,y=n,fill=factor(Survivorship,levels=c("Dead","Alive","Unknown"))))+geom_col()+coord_polar(theta="y",start=0)+xlim(c(0,2))+theme(plot.title=element_text(hjust=0.5),panel.background=element_rect(fill="transparent",color=NA),plot.background=element_rect(fill="transparent",color=NA),panel.grid=element_blank(),axis.title=element_blank(),axis.ticks=element_blank(),axis.text=element_blank(),legend.position=c(0.5,0.5),legend.title=element_blank(),legend.key=element_rect(fill="transparent",color=NA,linewidth=1.5),legend.text=element_text(size=14),legend.background=element_rect(fill="transparent",color=NA))+scale_fill_manual(values=c("Dead"="#03627e","Alive"="#2fb6de","Unknown"="#afe2f1"))+ggtitle("a) Survivorship")

# b)
sex=BWC_Neotropics%>%count(Sex)%>%arrange(desc(n));ggplot(sex,aes(x=1.5,y=n,fill=factor(Sex,levels=c("Unknown","Male","Female"))))+geom_col()+coord_polar(theta="y",start=0)+xlim(c(0,2))+theme(plot.title=element_text(hjust=0.5),panel.background=element_rect(fill="transparent",color=NA),plot.background=element_rect(fill="transparent",color=NA),panel.grid=element_blank(),axis.title=element_blank(),axis.ticks=element_blank(),axis.text=element_blank(),legend.position=c(0.5,0.5),legend.title=element_blank(),legend.key=element_rect(fill="transparent",color=NA,linewidth=1.5),legend.text=element_text(size=14),legend.background=element_rect(fill="transparent",color=NA))+scale_fill_manual(values=c("Unknown"="#03627e","Male"="#2fb6de","Female"="#afe2f1"))+ggtitle("b) Sex")

# c)
age=BWC_Neotropics%>%count(Age)%>%arrange(desc(n));ggplot(age,aes(x=1.5,y=n,fill=factor(Age,levels=c("Unknown","Adult","Juvenile"))))+geom_col()+coord_polar(theta="y",start=0)+xlim(c(0,2))+theme(plot.title=element_text(hjust=0.5),panel.background=element_rect(fill="transparent",color=NA),plot.background=element_rect(fill="transparent",color=NA),panel.grid=element_blank(),axis.title=element_blank(),axis.ticks=element_blank(),axis.text=element_blank(),legend.position=c(0.5,0.5),legend.title=element_blank(),legend.key=element_rect(fill="transparent",color=NA,linewidth=1.5),legend.text=element_text(size=14),legend.background=element_rect(fill="transparent",color=NA))+scale_fill_manual(values=c("Unknown"="#03627e","Adult"="#2fb6de","Juvenile"="#afe2f1"))+ggtitle("c) Age")

# d)
deterrent=BWC_Neotropics%>%count(Deterrent)%>%arrange(desc(n));ggplot(deterrent,aes(x=1.5,y=n,fill=factor(Deterrent,levels=c("None","Unknown","Present"))))+geom_col()+coord_polar(theta="y",start=0)+xlim(c(0,2))+theme(plot.title=element_text(hjust=0.5),panel.background=element_rect(fill="transparent",color=NA),plot.background=element_rect(fill="transparent",color=NA),panel.grid=element_blank(),axis.title=element_blank(),axis.ticks=element_blank(),axis.text=element_blank(),legend.position=c(0.5,0.5),legend.title=element_blank(),legend.key=element_rect(fill="transparent",color=NA,linewidth=1.5),legend.text=element_text(size=14),legend.background=element_rect(fill="transparent",color=NA))+scale_fill_manual(values=c("None"="#03627e","Unknown"="#2fb6de","Present"="#afe2f1"))+ggtitle("d) Deterrents")

# e)
building_height=BWC_Neotropics%>%count(Building.height)%>%arrange(desc(n));ggplot(building_height,aes(x=1.5,y=n,fill=factor(Building.height,levels=c("Low-rise","Taller","Unknown"))))+geom_col()+coord_polar(theta="y",start=0)+xlim(c(0,2))+theme(plot.title=element_text(hjust=0.5),panel.background=element_rect(fill="transparent",color=NA),plot.background=element_rect(fill="transparent",color=NA),panel.grid=element_blank(),axis.title=element_blank(),axis.ticks=element_blank(),axis.text=element_blank(),legend.position=c(0.5,0.5),legend.title=element_blank(),legend.key=element_rect(fill="transparent",color=NA,linewidth=1.5),legend.text=element_text(size=14),legend.background=element_rect(fill="transparent",color=NA))+scale_fill_manual(values=c("Low-rise"="#03627e","Taller"="#2fb6de","Unknown"="#afe2f1"))+ggtitle("e) Building height")

# f)
pane_type=BWC_Neotropics%>%count(Pane.type)%>%arrange(desc(n));ggplot(pane_type,aes(x=1.5,y=n,fill=factor(Pane.type,levels=c("Translucent","Unknown","Reflective"))))+geom_col()+coord_polar(theta="y",start=0)+xlim(c(0,2))+theme(plot.title=element_text(hjust=0.5),panel.background=element_rect(fill="transparent",color=NA),plot.background=element_rect(fill="transparent",color=NA),panel.grid=element_blank(),axis.title=element_blank(),axis.ticks=element_blank(),axis.text=element_blank(),legend.position=c(0.5,0.5),legend.title=element_blank(),legend.key=element_rect(fill="transparent",color=NA,linewidth=1.5),legend.text=element_text(size=14),legend.background=element_rect(fill="transparent",color=NA))+scale_fill_manual(values=c("Translucent"="#03627e","Unknown"="#2fb6de","Reflective"="#afe2f1"))+ggtitle("f) Pane type")

# g)
IUCN_status=BWC_Neotropics%>%count(IUCN.status)%>%arrange(desc(n));ggplot(IUCN_status,aes(x=1.5,y=n,fill=factor(IUCN.status,levels=c("Least Concern","Near Threatened","Vulnerable"))))+geom_col()+coord_polar(theta="y",start=0)+xlim(c(0,2))+theme(plot.title=element_text(hjust=0.5),panel.background=element_rect(fill="transparent",color=NA),plot.background=element_rect(fill="transparent",color=NA),panel.grid=element_blank(),axis.title=element_blank(),axis.ticks=element_blank(),axis.text=element_blank(),legend.position=c(0.5,0.5),legend.title=element_blank(),legend.key=element_rect(fill="transparent",color=NA,linewidth=1.5),legend.text=element_text(size=14),legend.background=element_rect(fill="transparent",color=NA))+scale_fill_manual(values=c("Least Concern"="#03627e","Near Threatened"="#2fb6de","Vulnerable"="#afe2f1"))+ggtitle("g) IUCN status")

# h)
method=BWC_Neotropics%>%count(Data.collection.method)%>%arrange(desc(n));ggplot(method,aes(x=1.5,y=n,fill=factor(Data.collection.method,levels=c("Systematic","By chance","Gov. Agency","Others","Unknown"))))+geom_col()+coord_polar(theta="y",start=0)+xlim(c(0,2))+theme(plot.title=element_text(hjust=0.5),panel.background=element_rect(fill="transparent",color=NA),plot.background=element_rect(fill="transparent",color=NA),panel.grid=element_blank(),axis.title=element_blank(),axis.ticks=element_blank(),axis.text=element_blank(),legend.position=c(0.5,0.5),legend.title=element_blank(),legend.key=element_rect(fill="transparent",color=NA,linewidth=1.5),legend.text=element_text(size=14),legend.background=element_rect(fill="transparent",color=NA))+scale_fill_manual(values=c("Systematic"="#000","By chance"="#044456","Gov. Agency"="#03627e","Others"="#2fb6de","Unknown"="#afe2f1"))+ggtitle("h) Data collection method")

# This R code was developed by Ian MacGregor-Fors on February 2025
